services:
  # --- Serviço do Banco de Dados MySQL ---
  mysql-db:
    image: mysql:latest
    container_name: mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: 'DecolaVagas2025.'
      MYSQL_DATABASE: 'DecolaVagas'
      MYSQL_USER: 'mateus'
      MYSQL_PASSWORD: 'Decola2025.'
      TZ: America/Sao_Paulo
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - network-db

  # --- Serviço do phpMyAdmin ---
  phpmyadmin:
    image: phpmyadmin:latest
    container_name: phpmyadmin
    restart: unless-stopped
    ports:
      - "3310:80"
    environment:
      PMA_HOST: 'mysql-db'
      MYSQL_ROOT_PASSWORD: 'DecolaVagas2025.'
      TZ: America/Sao_Paulo
    networks:
      - network-db
    depends_on:
      - mysql-db

volumes:
  mysql-data:

networks:
  network-db:
    driver: bridge